//说明需要的动作操作
export const GET_TAG_LIST_SUCCESS = 'GET_TAG_LIST_SUCCESS'
export const GET_TAG_LIST_FAILURE = 'GET_TAG_LIST_FAILURE'
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS'

export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST'
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE'
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const ARTICLE_LIST = 'ARTICLE_LIST'